### ISSUE TITLE
webdrive cannot cope with spaces in the path

### ISSUE THREAD

**Issue by jimAScott** [webdriverio/gulp-webdriver#26]
I am trying to use the gulp-webdriver in a path that sits under C:\program files\ I am getting an error saying that 'C:\Program' is not recognized as an internal or external command. When I move it to a location that has no spaces in the path it runs ok.

Unfortunately where I want to run it on the server has to have spaces in so is there a way of running this in a path with spaces?

**Comment by dhoulker** [comment]
I'm having the same issue - it looks like this is windows specific. 

`gutil.log('spawn wdio with these attributes:\n', args.join('\n'));`
   `var wdio = spawn(opts.wdioBin, args, {
            stdio: 'inherit'
        });`

It looks like where spawn is called, the 'args' argument is the path to the wdio conf file. If that path contains a space then the error above occurs.

**Comment by dhoulker** [comment]
Incase this issue is affecting anyone else - we found a workaround. 

The problem was specifically on our CI server, where we couldn't control the path from where the tests ran. 

The tests were running from `c:\program files\etc\etc\` and the space caused the issue. We found that if we cd'd to the short version `C:\Progra~1\etc\etc\` before kicking off the tests everything worked fine.

**Comment by hao-peng-sdl** [comment]
Amazing workaround!

**Comment by christian-bromann** [comment]
I think this is resolved then.
