### ISSUE TITLE
v2 (gulp-webdriver with WebdriverIO v4)

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/gulp-webdriver#38]
some requirements:
- [ ] bump WebdriverIO  version to latest
- [ ] add Babel to enable ES2016 compatible syntax (see [wdio-mocha-framework](htps://github.com/webdriverio/wdio-mocha-framework) as example)
- [ ] add Grunt for task management (Gulp is fine too but it is easier to just copy from existing project structures like that one above)
- [ ] instead of launching wdio as process, require the webdriverio launcher package and run wdio manually
- [ ] adapt integration tests (have at minimum a simple test run using the mocha or jasmine framework)
- [ ] integrate codeclimate (should be done by one of the maintainers)
- [ ] if website isn't updated add disclaimer with information how to use

**Comment by kevinlambert** [comment]
Functionality implemented on #39 
- [x] bump WebdriverIO version to latest
- [x] add Babel to enable ES2016 compatible syntax (see wdio-mocha-framework as example)
- [x] add Grunt for task management (Gulp is fine too but it is easier to just copy from existing project structures like that one above)
- [x] instead of launching wdio as process, require the webdriverio launcher package and run wdio manually
- [x] adapt integration tests (have at minimum a simple test run using the mocha or jasmine framework)
- [ ] integrate codeclimate (should be done by one of the maintainers)
- [ ] if website isn't updated add disclaimer with information how to use

**Comment by christian-bromann** [comment]
Thanks! I can take over the last two tasks.
